# Generated by Django 6.0.3 on 2026-03-12 13:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#4361ee', max_length=20)),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('heure_ouverture_matin', models.TimeField(default='08:00')),
                ('heure_fermeture_matin', models.TimeField(default='12:00')),
                ('heure_ouverture_apres_midi', models.TimeField(default='13:30')),
                ('heure_fermeture_apres_midi', models.TimeField(default='17:30')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur')], default='user', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DemandeModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=10)),
                ('cible', models.CharField(choices=[('employe', 'Employé'), ('site', 'Site'), ('poste', 'Poste')], max_length=20)),
                ('cible_id', models.IntegerField(blank=True, null=True)),
                ('donnees', models.JSONField(default=dict)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de modification',
                'verbose_name_plural': 'Demandes de modification',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pointage', models.DateField()),
                ('periode', models.CharField(choices=[('matin', 'Matin'), ('apres_midi', 'Après-midi'), ('nuit', 'Nuit')], max_length=20)),
                ('type_journee', models.CharField(choices=[('normal', 'Journée normale'), ('garde', 'Garde de nuit')], db_index=True, default='normal', max_length=20)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('retard', models.DurationField(blank=True, null=True)),
                ('heures_travaillees', models.DurationField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'En retard'), ('congé', 'Congé'), ('maladie', 'Maladie')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='pointage.employe')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='pointage.site')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date_pointage', 'periode', 'employe'],
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='pointage.poste'),
        ),
        migrations.AddField(
            model_name='employe',
            name='sites',
            field=models.ManyToManyField(related_name='employes', to='pointage.site'),
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type_scan', models.CharField(blank=True, choices=[('entree_matin', 'Entrée matin'), ('sortie_matin', 'Sortie matin'), ('entree_apres_midi', 'Entrée après-midi'), ('sortie_apres_midi', 'Sortie après-midi'), ('debut_garde', 'Début garde (nuit)'), ('fin_garde', 'Fin garde (nuit)')], max_length=20, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='pointage.employe')),
                ('pointage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='pointage.pointage')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='pointage.site')),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='pointage_sc_timesta_81e812_idx'), models.Index(fields=['employe', 'timestamp'], name='pointage_sc_employe_6e1e1a_idx'), models.Index(fields=['type_scan', 'timestamp'], name='pointage_sc_type_sc_ede95c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['date_pointage'], name='pointage_po_date_po_cfbe3b_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['employe', 'date_pointage'], name='pointage_po_employe_63aa08_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['statut', 'date_pointage'], name='pointage_po_statut_9db5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['site', 'date_pointage'], name='pointage_po_site_id_0891f6_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['type_journee'], name='pointage_po_type_jo_a7d5cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pointage',
            unique_together={('employe', 'date_pointage', 'periode')},
        ),
    ]
