# Generated by Django 5.2.3 on 2026-07-09 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QR_INVALIDE', 'QR code invalide'), ('SITE_NON_AUTORISE', 'Site non autorisé'), ('HORS_PLAGE', 'Scan hors plage horaire'), ('SCAN_EXCESS', 'Scan excédentaire (> 4/jour)'), ('SCAN_MANQUANT', 'Scan(s) manquant(s) en fin de journée'), ('DOUBLON', 'Scan dupliqué'), ('SORTIE_ANTICIPEE', 'Sortie anticipée autorisée'), ('SORTIE_NON_AUTORISEE', 'Sortie anticipée non autorisée')], db_index=True, max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('traitee', models.BooleanField(default=False)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerte RH',
                'verbose_name_plural': 'Alertes RH',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AutorisationSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveSmallIntegerField()),
                ('annee', models.PositiveSmallIntegerField()),
                ('utilisee', models.BooleanField(default=False)),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('heure_depart_reel', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Autorisation de sortie anticipée',
                'verbose_name_plural': 'Autorisations de sortie anticipée',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='demandemodification',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='pointage.customuser'),
        ),
        migrations.AlterField(
            model_name='demandemodification',
            name='traitee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='pointage.customuser'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['matricule', 'actif'], name='pointage_em_matricu_cf9f09_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['employe', 'periode', 'type_journee', 'heure_depart'], name='pointage_po_employe_8c0cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['date_pointage', 'periode', 'retard'], name='pointage_po_date_po_34915c_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['date_pointage', 'heure_arrivee'], name='pointage_po_date_po_32bcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['date_pointage', 'heure_depart'], name='pointage_po_date_po_ad4285_idx'),
        ),
        migrations.AddField(
            model_name='alerterh',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='pointage.employe'),
        ),
        migrations.AddField(
            model_name='alerterh',
            name='traitee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to='pointage.customuser'),
        ),
        migrations.AddField(
            model_name='autorisationsortie',
            name='confirme_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorisations_confirmees', to='pointage.customuser'),
        ),
        migrations.AddField(
            model_name='autorisationsortie',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorisations_sortie', to='pointage.employe'),
        ),
        migrations.AddField(
            model_name='autorisationsortie',
            name='pointage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorisation_sortie', to='pointage.pointage'),
        ),
        migrations.AddIndex(
            model_name='alerterh',
            index=models.Index(fields=['type', 'timestamp'], name='pointage_al_type_48c02d_idx'),
        ),
        migrations.AddIndex(
            model_name='alerterh',
            index=models.Index(fields=['traitee', 'timestamp'], name='pointage_al_traitee_c96aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='alerterh',
            index=models.Index(fields=['employe', 'timestamp'], name='pointage_al_employe_e8e165_idx'),
        ),
        migrations.AddIndex(
            model_name='autorisationsortie',
            index=models.Index(fields=['employe', 'annee', 'mois'], name='pointage_au_employe_dadbc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='autorisationsortie',
            unique_together={('employe', 'mois', 'annee')},
        ),
    ]
