# Generated by Django 5.2.3 on 2026-07-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_alerterh_autorisationsortie_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='autorisationsortie',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='autorisationsortie',
            name='pointage_au_employe_dadbc8_idx',
        ),
        migrations.RemoveField(
            model_name='autorisationsortie',
            name='confirme_par',
        ),
        migrations.RemoveField(
            model_name='autorisationsortie',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='autorisationsortie',
            name='pointage',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='sites',
        ),
        migrations.DeleteModel(
            name='AlerteRH',
        ),
        migrations.DeleteModel(
            name='AutorisationSortie',
        ),
    ]
