# Generated by Django 5.2.3 on 2026-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0003_alter_autorisationsortie_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='date_depart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
