# Generated by Django 5.2.3 on 2026-08-13 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pointage', '0006_anomalietraitement_type_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='anomaliepointage',
            name='matricule_scanne',
            field=models.CharField(blank=True, help_text="Matricule brut du QR scanné, conservé même si l'employé n'a pas pu être identifié (ex: QR invalide).", max_length=50),
        ),
        migrations.AlterField(
            model_name='anomalietraitement',
            name='date_traitement',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='anomalietraitement',
            name='type_action',
            field=models.CharField(choices=[('correction', 'Correction du pointage'), ('justification', 'Justification'), ('rejet', 'Rejet'), ('cloture', 'Clôture')], default='correction', max_length=20, verbose_name="Type d'action"),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to='pointage.employe'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointages', to='pointage.site'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='pointage.employe'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='pointage.site'),
        ),
    ]
