# Generated by Django 5.2.3 on 2026-08-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0007_phase1_2_18_customuser_anomalie_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalietraitement',
            name='type_action',
            field=models.CharField(choices=[('correction', 'Correction du pointage'), ('justification', 'Justification'), ('rejet', 'Rejet')], default='correction', max_length=20, verbose_name="Type d'action"),
        ),
    ]
