# Generated by Django 5.2.3 on 2026-08-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0009_alter_anomaliepointage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaliepointage',
            name='type',
            field=models.CharField(choices=[('invalid_qr', 'QR invalide'), ('employe_inactif', 'Employé inactif'), ('site_invalide', 'Site invalide'), ('hors_plage_globale', 'Hors plage horaire globale'), ('duplicate_scan', 'Double scan'), ('outside_hours', 'Hors horaires du site'), ('during_break', 'Scan pendant la pause'), ('day_complete', 'Journée déjà terminée'), ('missing_morning_exit', 'Sortie matin manquante'), ('transition_impossible', 'Transition impossible'), ('invalid_state', 'État invalide'), ('garde_multiple_non_supportee', 'Deuxième garde le même jour non prise en charge'), ('depart_anticipe', 'Départ anticipé')], max_length=30),
        ),
    ]
