# Generated by Django 5.2.3 on 2026-08-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0010_add_depart_anticipe_anomalie'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='employe',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
    ]
