# Generated by Django 5.2.3 on 2026-09-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0011_add_employe_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='heures_supplementaires',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='seuil_depart_anticipe_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Nombre de minutes avant la fermeture officielle au-delà duquel une sortie déclenche une anomalie "Départ anticipé". Laisser vide pour utiliser la valeur par défaut du système (15 min).', null=True, verbose_name='Seuil départ anticipé (minutes)'),
        ),
        migrations.AddField(
            model_name='site',
            name='tolerance_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Marge acceptée avant/après les horaires du site pour accepter un scan (ex : arriver 10 min avant l'ouverture reste accepté). Laisser vide pour utiliser la valeur par défaut du système (15 min).", null=True, verbose_name='Tolérance (minutes)'),
        ),
    ]
