# Generated by Django 5.2.17 on 2026-09-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0017_alter_site_tolerance_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='client_event_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
