# Generated by Django 5.2.17 on 2026-09-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0024_drop_overtime_zero_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandemodification',
            name='cible',
            field=models.CharField(choices=[('employe', 'Employé'), ('site', 'Site'), ('poste', 'Poste'), ('utilisateur', 'Mon compte')], max_length=20),
        ),
    ]
