# Generated by Django 5.x
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pointage", "0030_horaires_garde"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationpointage",
            name="heure_bascule_apres_midi",
            field=models.TimeField(
                default="12:00",
                help_text="Heure utilisée par l'interface Web pour déterminer l'affichage de la période courante.",
                verbose_name="Bascule matin → après-midi",
            ),
        ),
    ]
