# Generated by Django 5.x
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ("pointage", "0031_configuration_bascule_apres_midi"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationpointage",
            name="duree_journee_reference",
            field=models.DurationField(
                default=datetime.timedelta(hours=8),
                help_text="Utilisée pour les synthèses et exports qui comparent le temps travaillé à une journée de référence.",
                verbose_name="Durée de référence d'une journée",
            ),
        ),
    ]
